#!/bin/bash
# 演示脚本 - 用于录制演示视频

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   Feishu Send File - OpenClaw Skill Demo                  ║"
echo "║   飞书文件直发工具 - 演示                                   ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# 创建演示文件
echo "📝 Step 1: Create a sample file..."
echo "This is a demo file for Feishu Send File skill." > /tmp/demo.txt
echo "Generated by OpenClaw Agent - Henry" >> /tmp/demo.txt
echo "Date: $(date)" >> /tmp/demo.txt
echo "✅ Sample file created: /tmp/demo.txt"
echo ""
sleep 2

# 显示文件内容
echo "📄 Step 2: File content preview..."
cat /tmp/demo.txt
echo ""
sleep 2

# 发送文件
echo "🚀 Step 3: Send file to Feishu..."
echo ""
sleep 1

# 这里使用实际的发送命令(演示时替换为真实的 open_id)
export FEISHU_APP_ID="cli_a91404216f395bde"
export FEISHU_APP_SECRET="REUTcPTZuN0qJ8ZbBdAAzhNv5O56Zduc"

/root/.openclaw/workspace/skills/feishu-send-file/send-file-wrapper.sh \
  ou_0765c32b5ec622535c5ccc284982cfe5 \
  /tmp/demo.txt

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║   ✅ Demo completed!                                       ║"
echo "║   Check your Feishu chat for the file 🎉                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
